name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: igorbaratta/mtspy
    steps:
      - name: git Actions
        uses: srt32/git-actions@v0.0.3
      - uses: actions/checkout@v2
        with:
          submodules: recursive         
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
      - name: Verify pep8, pyflakes and circular complexity
        run: flake8 mtspy
      - name: Install mtspy
        run: python3 -m pip install -v .
      - name: Run unit tests
        run: python3 -m pytest -v tests/
    
