name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: igorbaratta/mtspy
    steps:
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2
    
