name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: igorbaratta/mtspy
    steps:
      - name: git Actions
        uses: srt32/git-actions@v0.0.3
      - name: Setup file system permissions
        run: chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2
        with:
          submodules: recursive         
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov coveralls
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Verify pep8, pyflakes and circular complexity
        run: flake8 mtspy
      - name: Install mtspy
        run: python3 -m pip install -v .
      - name: Test 
        run: |
            pytest ./tests --cov=mtspy
            coveralls
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
              github-token: ${{ secrets.GITHUB_TOKEN }}

    
